# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_livesession_chatmessage_liveparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='recording', max_length=12)),
                ('video_file', models.FileField(blank=True, upload_to='recordings/video/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='lectures.lecture')),
            ],
        ),
    ]
