# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_livesession_chatmessage_liveparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('start_ms', models.PositiveBigIntegerField(default=0)),
                ('end_ms', models.PositiveBigIntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='lectures.lecture')),
            ],
            options={
                'ordering': ['start_ms'],
            },
        ),
    ]
