# Generated by Django 5.2.17 on 2026-09-01 16:05

import django.db.models.deletion
import lectures.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], default='private', max_length=10)),
                ('share_token', models.CharField(default=lectures.models.share_code, editable=False, max_length=32, unique=True)),
                ('video', models.FileField(blank=True, upload_to='lectures/video/')),
                ('audio', models.FileField(blank=True, upload_to='lectures/audio/')),
                ('attachment', models.FileField(blank=True, upload_to='lectures/files/')),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lectures.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_drawing', models.TextField(help_text='Canvas image as a data URL')),
                ('recognized_text', models.TextField(blank=True)),
                ('drawing_type', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='lectures.lecture')),
            ],
        ),
    ]
