# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.JSONField(default=dict)),
                ('color_lower', models.JSONField(default=list)),
                ('color_upper', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='camera.cameradevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_calibrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
