# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_livesession_chatmessage_liveparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('canvas_data', models.TextField(blank=True)),
                ('recognized_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_pages', to='lectures.lecture')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lecture', 'page_number'), name='unique_board_page')],
            },
        ),
    ]
