# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_livesession_chatmessage_liveparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ocr', 'OCR'), ('summary', 'Summary'), ('diagram', 'Diagram'), ('answer', 'Answer suggestion')], max_length=12)),
                ('input_reference', models.CharField(blank=True, max_length=255)),
                ('output_text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artifacts', to='lectures.lecture')),
            ],
        ),
    ]
