# Generated by Django 5.2.17 on 2026-09-01 18:25

import django.db.models.deletion
import sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_livesession_chatmessage_liveparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=sharing.models.share_token, editable=False, max_length=64, unique=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='lectures.lecture')),
            ],
        ),
    ]
